### ISSUE TITLE
Client not loading configurations

### ISSUE THREAD

**Issue by KuroNoSeiHai** [ProjectEssentials/ProjectEssentials-Core#10] opened 2020-06-05 14:16 UTC
1.15.2 when install core and protection with worldedit, it will crash when you use wand tools right click to choose position.
Below is debug.log and crash report
[debug.log](https://github.com/ProjectEssentials/ProjectEssentials-Core/files/4736576/debug.log)
[crash-2020-06-05_21.42.24-client.txt](https://github.com/ProjectEssentials/ProjectEssentials-Core/files/4736578/crash-2020-06-05_21.42.24-client.txt)

**Comment by MairwunNx** [comment] 2020-06-05 15:14
You was in single player or join to server with mods?

**Comment by MairwunNx** [comment] 2020-06-05 15:20
Client loads configurations correctly. I'll try reproduce this by connecting on server with mods.

**Comment by MairwunNx** [comment] 2020-06-05 15:22
Can't reproduce this bug with 1.14.4, you can reproduce this?

**Comment by KuroNoSeiHai** [comment] 2020-06-05 16:00
I join to server with mods, client crashed but server is not.

**Comment by MairwunNx** [comment] 2020-06-05 17:47
Hm, if you can, try reproduce this again. I'll test this on 1.15.2 later

Thank you for testing!

**Comment by KuroNoSeiHai** [comment] 2020-06-06 13:49
Fixed. And I updated translation.

**Comment by MairwunNx** [comment] 2020-06-06 22:08
If this issue not actual for you, you can close this =), thanks.

**Comment by MairwunNx** [comment] 2020-06-10 09:22
Please, open this if that issue will reproduces, thank you!

**Closed as completed by MairwunNx** 2020-06-10 09:22 UTC
Labels: bug, can't reproduce, investigate
